version: "3.8"

services:
  pypi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - pypi_db
    command: >
      sh -c "uvicorn server:app --host 0.0.0.0 --port 8080"
    networks:
      - web
    env_file:
      - .env.prod
    labels:
      - traefik.enable=true
      - traefik.http.services.pypi_app.loadbalancer.server.port=8080
      - traefik.http.routers.pypi_app.rule=Host(`pypi.shorten.ru.com`)
      - traefik.http.routers.pypi_app.tls=true
      - traefik.http.routers.pypi_app.tls.certresolver=lets-encrypt

  pypi_db:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - web
      env_file:
        - .env.prod
      volumes:
        - postgres_data_pypi:/var/lib/postgresql/data/

volumes:
  postgres_data_pypi:

networks:
  web:
    external: true
